### ISSUE TITLE
Deployment question

### ISSUE THREAD

**Issue by joshdvir** [gre/screenshot-webservice#12]
Is it possible to deploy it to heroku ? 
http://heroku.com

Thanks

**Comment by gre** [comment]
Hi,

First, AFAIK A Play application is deployable on Heroku.
For this app there is only a specific dependency on "phantomjs" as a CLI command.

But apparently you can install PhantomJS with https://github.com/stomita/heroku-buildpack-phantomjs

I haven't tested it.

**Comment by robcowell** [comment]
I suspect you'd have to use [heroku-buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi) to combine the standard Play/Scala build with the PhantomJS one so they place nice together.  See the note at the bottom of the README for the PhantomJS GitHub page for details

**Comment by joshdvir** [comment]
Thanks.
